package com.smart.demo_smart.demo;


/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person2 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer age;
	private java.lang.String label;

	private java.lang.Integer gender;

	private Profession2 profession;

	private java.lang.String name;

	private java.lang.Boolean marriged;

	public Person2() {
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.String getLabel() {
		return this.label;
	}

	public void setLabel(java.lang.String label) {
		this.label = label;
	}

	public java.lang.Integer getGender() {
		return this.gender;
	}

	public void setGender(java.lang.Integer gender) {
		this.gender = gender;
	}

	public Profession2 getProfession() {
		return this.profession;
	}

	public void setProfession(Profession2 profession) {
		this.profession = profession;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Boolean getMarriged() {
		return this.marriged;
	}

	public void setMarriged(java.lang.Boolean marriged) {
		this.marriged = marriged;
	}

	public Person2(java.lang.Integer age, java.lang.String label,
			java.lang.Integer gender,
			Profession2 profession,
			java.lang.String name, java.lang.Boolean marriged) {
		this.age = age;
		this.label = label;
		this.gender = gender;
		this.profession = profession;
		this.name = name;
		this.marriged = marriged;
	}

}