package com.smart.demo_smart.demo;

import org.kie.api.definition.type.Label;

/**
 * This class was automatically generated by the data modeler tool.
 */

//@javax.persistence.Entity
public class Profession2 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String grade;

	private java.lang.String title;

	public Profession2() {
	}

	public java.lang.String getGrade() {
		return this.grade;
	}

	public void setGrade(java.lang.String grade) {
		this.grade = grade;
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public Profession2(java.lang.String grade, java.lang.String title) {
		this.grade = grade;
		this.title = title;
	}

}