version: '2'
services:
  drools-workbench:
    image: jboss/drools-workbench-showcase:latest
    ports:
      - "8101:8001"
      - "8102:8080"
    networks:
      - "netNameRuleEngine"
    volumes:
      - /opt/jrdn/rule-engine/repository/:/opt/jboss/.m2/repository
    restart: always
  kie-server:
    image: jboss/kie-server-showcase:latest
    ports:
      - "8103:8080"
    networks:
      - "netNameRuleEngine"
    restart: always
  drool-rule:
    image: registry.cn-shanghai.aliyuncs.com/jrdn/drool-rule:0.0.1-SNAPSHOT
    ports:
      - "8104:8080"
    networks:
      - "netNameRuleEngine"
    restart: always
networks:
  netNameRuleEngine:
    driver: bridge

