spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://112.65.210.194:443/outdb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: msp
      password: fghjiodfod2)__ABC
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
#      max-evictable-idle-time-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      # validation-query-timeout: 5000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #filters: #配置多个英文逗号分隔(统计，sql注入，log4j过滤)
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*

kie-server:
  #url: http://172.22.211.140:8103/kie-server/services/rest/server
  url: http://112.65.210.206:8103/kie-server/services/rest/server
  username: admin
  password: admin
  kie-container-id: demo-smart
  session-id: session2


swagger:
  enable: true