// 导入类
import com.drool.engine.entity.Person
dialect  "mvel"

// 规则名，唯一
rule "age"
    when
        //规则的条件部分
        $person : Person(age<16 || age>50)
    then
        $person.setResp("未通过审核");
        System.out.println($person.getName()+":的年龄为"+$person.getAge()+"====不符合要求！");
end

// 规则名，唯一
rule "rightAge"
    when
        //规则的条件部分
        $person : Person(age>=16 && age<=50)
    then
        $person.setResp("通过审核");
        System.out.println($person.getName()+":的年龄为"+$person.getAge()+"====符合要求！");
end