package droolsexample
import com.drool.engine.entity.ItemCity;
import java.math.BigDecimal;

rule "Nagpur Medicine Item"
    when item : ItemCity(purchaseCity == ItemCity.City.NAGPUR, typeofItem == ItemCity.Type.MEDICINES)
    then BigDecimal tax = new BigDecimal(0.0);
        item.setLocalTax(tax.multiply(item.getSellPrice()));
end

rule "Nagpur Groceries Item"
    when item : ItemCity(purchaseCity == ItemCity.City.NAGPUR, typeofItem == ItemCity.Type.GROCERIES)
    then BigDecimal tax = new BigDecimal(0.23);
        item.setLocalTax(tax.multiply(item.getSellPrice()));
end
